name: 📦Auto Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  id-token: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Create zip archive
        run: zip -r "ModernEase-${TAG_NAME}.zip" . -x ".github/*" ".git/*" "README.md" ".gitignore"
      - name: Create tar.gz archive
        run: tar --exclude=.github --exclude=.git --exclude=README.md --exclude=.gitignore --exclude="ModernEase-${TAG_NAME}.zip" --ignore-failed-read -czf "ModernEase-${TAG_NAME}.tar.gz" .
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "${{ env.TAG_NAME }}"
          files: |
            ModernEase-${{ env.TAG_NAME }}.zip
            ModernEase-${{ env.TAG_NAME }}.tar.gz
